services:
    pgsql:
        image: 'postgres:17'
        ports:
            - '${FORWARD_DB_PORT:-5433}:5433'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'go-gms:/var/lib/postgresql/data'
        networks:
            - go-gms
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
networks:
    go-gms:
        driver: bridge
volumes:
    sail-go-gms:
        driver: local
